import { figtree } from './fonts/fonts'
import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${figtree.variable} font-figtree`}>
                {children}
            </body>
        </html>
    )
}
